# Database ??
spring:
  sql:
    init:
      mode: always  #data.sql ????? ????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tmdbmovieapp
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop  #???? ??? ??? drop?? ?? create?
    defer-datasource-initialization: true #data.sql ????? ????
    show-sql: true  #??? sql? ???
    properties:
      hibernate:
        format_sql: true  #?? sql? ? ???
        default_batch_fetch_size: 100 #selete? where ?? in ? ???? ?????? ??? ??? ????

# thymeleaf ??
  thymeleaf:
    cache: false

# Spring Actuator ??
management:
  endpoints:
    web:
      exposure:
        include: '*'

