# Database ??
spring:
  sql:
    init:
      mode: always  #data.sql ????? ????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tmdbmovieapp
    username: ${MYSQL_ID}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create  #???? ??? ??? drop?? ?? create?
    defer-datasource-initialization: true #data.sql ????? ????
    properties:
      hibernate:
        format_sql: true  #?? sql? ? ???
        default_batch_fetch_size: 100 #selete? where ?? in ? ???? ?????? ??? ??? ????

  # thymeleaf ??
  thymeleaf:
    cache: false
    # OAuth2 id, secret
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
  devtools:
    livereload:
      enabled: true
    restart:
      quiet-period: 900ms

  data:
    rest:
      base-path: /api
      detection-strategy: default
  profiles:
    include: API-KEY
  mvc:
    hiddenmethod:
      filter:
        enabled: true

# Spring Actuator ??
management:
  endpoints:
    web:
      exposure:
        include: '*'
debug: true
tmdb:
  api:
    key: ${TMDB_API_KEY}
